### ISSUE TITLE
SkillSound Packet not properly implemented for remaster client.

### ISSUE THREAD

**Issue by zajako** [zajako/LineageHD#174]
[GetPacket-Fail] Invalid Server Packet (S_SkillSound) for version 1
java.lang.NoSuchMethodException: l1j.server.network.v18123.serverpackets.S_SkillSound.<init>(int, char)
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.getConstructor(Class.java:1825)
        at l1j.server.network.GetPacket.getS_Overwrite(Unknown Source)
        at l1j.server.network.GetPacket.getS(Unknown Source)
        at l1j.server.server.model.Instance.L1PcInstance.sendPackets(Unknown Source)
        at l1j.server.server.command.executor.L1AddSkill.execute(Unknown Source)
        at l1j.server.server.GMCommands.executeDatabaseCommand(Unknown Source)
        at l1j.server.server.GMCommands.handleCommands(Unknown Source)
        at l1j.server.network.v18123.clientpackets.C_Craft.Chat(Unknown Source)
        at l1j.server.network.v18123.clientpackets.C_Craft.<init>(Unknown Source)
        at l1j.server.network.v18123.PacketHandler.handlePacket(Unknown Source)
        at l1j.server.network.v18123.PacketExecutor.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019.08.31 08:57:26,474 GameMaster commanded addskill

**Comment by zajako** [comment]
this should be fixed with the next test restart.
