### ISSUE TITLE
Scatterblaster isn't working right due to these errors.

### ISSUE THREAD

**Issue by zajako** [zajako/LineageHD#205]
GetPacket-Fail] Invalid Server Packet (S_DoActionGFX) for version 1
java.lang.NoSuchMethodException: l1j.server.network.v18123.serverpackets.S_DoActionGFX.<init>(int, java.lang.String)
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.getConstructor(Class.java:1825)
        at l1j.server.network.GetPacket.getS_Overwrite(Unknown Source)
        at l1j.server.network.GetPacket.getS(Unknown Source)
        at l1j.server.server.model.Instance.L1PcInstance.sendPackets(Unknown Source)
        at l1j.server.server.model.L1Attack.damageNpcWeaponDurability(Unknown Source)
        at l1j.server.server.model.L1Attack.commitNpc(Unknown Source)
        at l1j.server.server.model.L1Attack.commit(Unknown Source)
        at l1j.server.server.model.Instance.L1MonsterInstance.onAction(Unknown Source)
        at l1j.server.network.v18123.utils.AttackController.action(Unknown Source)
        at l1j.server.network.v18123.utils.AttackController.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)

[GetPacket-Fail] Invalid Server Packet (S_DoActionGFX) for version 1
java.lang.NoSuchMethodException: l1j.server.network.v18123.serverpackets.S_DoActionGFX.<init>(int, java.lang.String)
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.getConstructor(Class.java:1825)
        at l1j.server.network.GetPacket.getS_Overwrite(Unknown Source)
        at l1j.server.network.GetPacket.getS(Unknown Source)
        at l1j.server.server.model.Instance.L1PcInstance.sendPackets(Unknown Source)
        at l1j.server.server.model.L1Attack.damageNpcWeaponDurability(Unknown Source)
        at l1j.server.server.model.L1Attack.commitNpc(Unknown Source)
        at l1j.server.server.model.L1Attack.commit(Unknown Source)
        at l1j.server.server.model.Instance.L1MonsterInstance.onAction(Unknown Source)
        at l1j.server.network.v18123.utils.AttackController.action(Unknown Source)
        at l1j.server.network.v18123.utils.AttackController.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)
PlayerCommand: betanoob

**Comment by zajako** [comment]
Fixed with test server restart shortly
