### ISSUE TITLE
error when creating party

### ISSUE THREAD

**Issue by zajako** [zajako/LineageHD#261]
No Replace Found for S_Party Expecting: [class [Ll1j.server.server.model.Instance.L1PcInstance;] Using: [int]

[GetPacket-Fail] Invalid Server Packet (S_Party) for version 1
java.lang.NoSuchMethodException: l1j.server.network.v18123.serverpackets.S_Party.<init>(int, l1j.server.server.model.Instance.L1PcInstance)
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.getConstructor(Class.java:1825)
        at l1j.server.network.GetPacket.getS_Overwrite(Unknown Source)
        at l1j.server.network.GetPacket.getS(Unknown Source)
        at l1j.server.server.model.Instance.L1PcInstance.sendPackets(Unknown Source)
        at l1j.server.server.model.L1Party.showAddPartyInfo(Unknown Source)
        at l1j.server.server.model.L1Party.addMember(Unknown Source)
        at l1j.server.network.v18123.clientpackets.C_Attr.<init>(Unknown Source)
        at l1j.server.network.v18123.PacketHandler.handlePacket(Unknown Source)
        at l1j.server.network.v18123.PacketExecutor.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
        at l1j.server.server.model.Instance.L1PcInstance.sendPackets(Unknown Source)
        at l1j.server.server.model.Instance.L1PcInstance.sendPackets(Unknown Source)
        at l1j.server.server.model.L1Party.showAddPartyInfo(Unknown Source)
        at l1j.server.server.model.L1Party.addMember(Unknown Source)
        at l1j.server.network.v18123.clientpackets.C_Attr.<init>(Unknown Source)
        at l1j.server.network.v18123.PacketHandler.handlePacket(Unknown Source)
        at l1j.server.network.v18123.PacketExecutor.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by zajako** [comment]
Error is fixed, however mp bar doesn't seem to sync.  Life bars do show up and leader icon does too.
