### ISSUE TITLE
OUtOfBounds Exception with C_Rank

### ISSUE THREAD

**Issue by zajako** [zajako/LineageHD#27]
2019.03.09 06:00:07,946 OpCode=36
2019.03.09 06:00:07,946 java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at l1j.server.network.ClientBasePacket.readS(Unknown Source)
	at l1j.server.network.ClientBasePacket.readS(Unknown Source)
	at l1j.server.network.v18123.clientpackets.C_Rank.<init>(Unknown Source)
	at l1j.server.network.v18123.PacketHandler.handlePacket(Unknown Source)
	at l1j.server.network.v18123.PacketExecutor.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zajako** [comment]
This should be fixed now.
