### ISSUE TITLE
/join doesn't work, only -join

### ISSUE THREAD

**Issue by zajako** [zajako/LineageHD#284]
C_Clan Requesting embleimg with id: 880810243
java.lang.NullPointerException
        at l1j.server.network.v18123.clientpackets.C_JoinClan.JoinClan(Unknown Source)
        at l1j.server.network.v18123.clientpackets.C_JoinClan.<init>(Unknown Source)
        at l1j.server.network.v18123.PacketHandler.handlePacket(Unknown Source)
        at l1j.server.network.v18123.PacketExecutor.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
        at l1j.server.network.v18123.clientpackets.C_JoinClan.JoinClan(Unknown Source)
        at l1j.server.network.v18123.clientpackets.C_JoinClan.<init>(Unknown Source)
        at l1j.server.network.v18123.PacketHandler.handlePacket(Unknown Source)
        at l1j.server.network.v18123.PacketExecutor.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
        at l1j.server.network.v18123.clientpackets.C_JoinClan.JoinClan(Unknown Source)
        at l1j.server.network.v18123.clientpackets.C_JoinClan.<init>(Unknown Source)
        at l1j.server.network.v18123.PacketHandler.handlePacket(Unknown Source)
        at l1j.server.network.v18123.PacketExecutor.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by zajako** [comment]
This should be fixed with the next test server restart
