### ISSUE TITLE
Error on Delete Item

### ISSUE THREAD

**Issue by zajako** [zajako/LineageHD#291]
java.lang.ArrayIndexOutOfBoundsException: 12
	at l1j.server.network.ClientBasePacket.readD(Unknown Source)
	at l1j.server.network.v18123.clientpackets.C_DeleteInventoryItem.<init>(Unknown Source)
	at l1j.server.network.v18123.PacketHandler.handlePacket(Unknown Source)
	at l1j.server.network.v18123.PacketExecutor.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zajako** [comment]
This should be fixed now.
